import { Galeria, GaleriaConfiguracoes, RegrasCongeladas, GaleriaPhoto } from '../useSupabaseGalleries';

export function transformGaleria(row: any): Galeria {
  const configuracoes = (row.configuracoes as GaleriaConfiguracoes) || {};

  const coverPhotoKey: string | null = row.cover_storage_key || null;
  const firstPhotoKey: string | null = row.first_photo_storage_key || null;

  return {
    id: row.id,
    userId: row.user_id,
    clienteId: row.cliente_id,
    status: row.status,
    statusPagamento: row.status_pagamento,
    fotosIncluidas: row.fotos_incluidas,
    valorFotoExtra: row.valor_foto_extra,
    regrasSelecao: row.regras_selecao,
    prazoSelecaoDias: row.prazo_selecao_dias,
    createdAt: new Date(row.created_at),
    updatedAt: new Date(row.updated_at),
    publishedAt: row.published_at ? new Date(row.published_at) : null,
    finalizedAt: row.finalized_at ? new Date(row.finalized_at) : null,
    sessionId: row.session_id,
    orcamentoId: row.orcamento_id,
    permissao: row.permissao || 'private',
    nomeSessao: row.nome_sessao,
    nomePacote: row.nome_pacote,
    mensagemBoasVindas: row.mensagem_boas_vindas,
    configuracoes,
    totalFotos: row.total_fotos || 0,
    fotosSelecionadas: row.fotos_selecionadas || 0,
    valorExtras: row.valor_extras || 0,
    valorTotalVendido: row.valor_total_vendido || 0,
    totalFotosExtrasVendidas: row.total_fotos_extras_vendidas || 0,
    statusSelecao: row.status_selecao || 'em_andamento',
    prazoSelecao: row.prazo_selecao ? new Date(row.prazo_selecao) : null,
    enviadoEm: row.enviado_em ? new Date(row.enviado_em) : null,
    clienteNome: row.cliente_nome,
    clienteEmail: row.cliente_email,
    clienteTelefone: row.cliente_telefone || null,
    publicToken: row.public_token || null,
    galleryPassword: row.gallery_password || null,
    regrasCongeladas: row.regras_congeladas as RegrasCongeladas | null,
    regrasOverride: row.regras_override ?? false,
    tipo: row.tipo === 'entrega' ? 'entrega' : 'selecao',
    firstPhotoKey,
    coverPhotoKey,
    themeId: row.theme_id,
    useCustomTheme: row.use_custom_theme ?? false,
    themeOverrides: row.theme_overrides ?? {},
    coverId: row.cover_id ?? null,
    expiresAt: row.expires_at ? new Date(row.expires_at) : null,
    vendaModo: row.venda_modo ?? null,
    vendaPagamentoProvedor: row.venda_pagamento_provedor ?? null,
    vendaTipoCobranca: row.venda_tipo_cobranca ?? null,
  };
}

export function transformArchivedGaleria(row: any): Galeria {
  return {
    id: row.id,
    userId: row.user_id,
    clienteId: row.cliente_id,
    status: 'archived',
    statusPagamento: 'none',
    fotosIncluidas: row.fotos_incluidas || 0,
    valorFotoExtra: row.valor_foto_extra || 0,
    regrasSelecao: null,
    prazoSelecaoDias: null,
    createdAt: new Date(row.created_at),
    updatedAt: new Date(row.archived_at || row.created_at),
    publishedAt: null,
    finalizedAt: row.finalized_at ? new Date(row.finalized_at) : null,
    sessionId: row.session_id,
    orcamentoId: null,
    permissao: 'private',
    nomeSessao: row.nome_sessao || 'Galeria Arquivada',
    nomePacote: row.nome_pacote,
    mensagemBoasVindas: null,
    configuracoes: {},
    totalFotos: 0,
    fotosSelecionadas: row.fotos_selecionadas || 0,
    valorExtras: 0,
    valorTotalVendido: row.valor_total_vendido || 0,
    totalFotosExtrasVendidas: row.total_fotos_extras_vendidas || 0,
    statusSelecao: 'arquivada',
    prazoSelecao: null,
    enviadoEm: null,
    clienteNome: null,
    clienteEmail: null,
    clienteTelefone: null,
    publicToken: null,
    galleryPassword: null,
    regrasCongeladas: null,
    regrasOverride: false,
    tipo: row.tipo || 'selecao',
    firstPhotoKey: null,
    coverPhotoKey: null,
    vendaModo: null,
    vendaPagamentoProvedor: null,
    vendaTipoCobranca: null,
  } as Galeria;
}

export function transformPhoto(row: any): GaleriaPhoto {
  return {
    id: row.id,
    galeriaId: row.galeria_id,
    userId: row.user_id,
    filename: row.filename,
    originalFilename: row.original_filename,
    fileSize: row.file_size,
    mimeType: row.mime_type,
    width: row.width,
    height: row.height,
    storageKey: row.storage_key,
    isSelected: row.is_selected,
    isFavorite: row.is_favorite ?? false,
    comment: row.comment,
    pesoVisual: row.peso_visual ?? 0,
    orderIndex: row.order_index,
    pastaId: row.pasta_id || null,
    createdAt: new Date(row.created_at),
    updatedAt: new Date(row.updated_at),
  };
}
