import type { FormularioCampo } from '@/types/formulario';

export interface FormularioSeedTemplate {
  slug: 'ensaio' | 'casamento' | 'gestante' | 'newborn' | 'evento';
  nome: string;
  descricao: string;
  categoria: string;
  emoji: string;
  tempo_estimado: number;
  campos: FormularioCampo[];
}

export const FORMULARIO_SEED_TEMPLATES: FormularioSeedTemplate[] = [
  {
    slug: 'ensaio',
    nome: 'Briefing — Ensaio Fotográfico',
    descricao: 'Formulário completo para ensaios individuais, casais ou famílias em estúdio e externas.',
    categoria: 'ensaio',
    emoji: '📸',
    tempo_estimado: 3,
    campos: [
      {
        id: 'e1',
        tipo: 'texto_curto',
        label: 'Quem participará do ensaio?',
        placeholder: 'Ex: Eu e meu marido / Eu sozinha(o)',
        ordem: 1,
        obrigatorio: true,
        descricao: 'Informe o nome dos participantes principais',
      },
      {
        id: 'e2',
        tipo: 'selecao_unica',
        label: 'Qual o estilo visual desejado?',
        placeholder: '',
        ordem: 2,
        obrigatorio: true,
        opcoes: ['Estúdio minimalista', 'Externo / Natureza', 'Urbano / Cidade', 'Lifestyle / Casa', 'Mix de estilos'],
        descricao: '',
      },
      {
        id: 'e3',
        tipo: 'texto_curto',
        label: 'Paleta de cores ou roupas planejadas',
        placeholder: 'Ex: tons terrosos, linho, jeans e branco',
        ordem: 3,
        obrigatorio: false,
        descricao: 'Nos ajuda a orientar e harmonizar os cenários',
      },
      {
        id: 'e4',
        tipo: 'upload_referencia',
        label: 'Fotos de inspiração ou referências',
        placeholder: 'Envie prints ou fotos que representem o que você busca',
        ordem: 4,
        obrigatorio: false,
        descricao: '',
      },
      {
        id: 'e5',
        tipo: 'texto_longo',
        label: 'Existe alguma pose, detalhe ou momento essencial?',
        placeholder: 'Conte o que você mais gostaria de destacar...',
        ordem: 5,
        obrigatorio: false,
        descricao: '',
      },
    ],
  },
  {
    slug: 'casamento',
    nome: 'Briefing — Casamento',
    descricao: 'Alinhamento completo com os noivos sobre cronograma, momentos-chave e padrinhos.',
    categoria: 'casamento',
    emoji: '💍',
    tempo_estimado: 4,
    campos: [
      {
        id: 'c1',
        tipo: 'texto_curto',
        label: 'Nome completo dos Noivos',
        placeholder: 'Ex: Camila & Leonardo',
        ordem: 1,
        obrigatorio: true,
        descricao: '',
      },
      {
        id: 'c2',
        tipo: 'texto_longo',
        label: 'Momentos que não podem faltar',
        placeholder: 'Ex: First look, entrada dos avós, primeira dança, votos emocionantes...',
        ordem: 2,
        obrigatorio: true,
        descricao: 'Liste os momentos mais importantes da cerimônia e festa',
      },
      {
        id: 'c3',
        tipo: 'texto_longo',
        label: 'Pessoas fundamentais para as fotos protocolares',
        placeholder: 'Ex: Bisavó Tereza (só fica até às 18h), padrinhos, tios...',
        ordem: 3,
        obrigatorio: true,
        descricao: 'Ajuda nossa equipe a priorizar os registros familiares',
      },
      {
        id: 'c4',
        tipo: 'texto_longo',
        label: 'Cronograma previsto do dia',
        placeholder: 'Ex: 15h Making of, 17h Cerimônia, 18h30 Ensaio dos Noivos, 19h30 Recepção',
        ordem: 4,
        obrigatorio: false,
        descricao: '',
      },
      {
        id: 'c5',
        tipo: 'upload_referencia',
        label: 'Referências visuais ou pasta de inspiração',
        placeholder: 'Envie imagens do estilo fotográfico que vocês amam',
        ordem: 5,
        obrigatorio: false,
        descricao: '',
      },
    ],
  },
  {
    slug: 'gestante',
    nome: 'Briefing — Ensaio Gestante',
    descricao: 'Coleta de dados da gestação, expectativas, bem-estar e produção.',
    categoria: 'gestante',
    emoji: '🤰',
    tempo_estimado: 3,
    campos: [
      {
        id: 'g1',
        tipo: 'data',
        label: 'Data prevista do parto (DPP)',
        placeholder: 'Selecione a data prevista',
        ordem: 1,
        obrigatorio: true,
        descricao: 'Fundamental para definirmos o período ideal do ensaio (entre 28 e 34 semanas)',
      },
      {
        id: 'g2',
        tipo: 'texto_curto',
        label: 'Nome do bebê (se já definido)',
        placeholder: 'Ex: Helena',
        ordem: 2,
        obrigatorio: false,
        descricao: '',
      },
      {
        id: 'g3',
        tipo: 'selecao_unica',
        label: 'Preferência de ambiente',
        placeholder: '',
        ordem: 3,
        obrigatorio: true,
        opcoes: ['Estúdio aconchegante', 'Ar livre / Golden Hour', 'No conforto da sua casa (Home)', 'Mix estúdio + externo'],
        descricao: '',
      },
      {
        id: 'g4',
        tipo: 'texto_curto',
        label: 'Quem participará com você?',
        placeholder: 'Ex: Esposo, filho mais velho e nosso pet',
        ordem: 4,
        obrigatorio: true,
        descricao: '',
      },
      {
        id: 'g5',
        tipo: 'upload_referencia',
        label: 'Inspirações de fotos e figurinos',
        placeholder: 'Envie referências que combinam com você',
        ordem: 5,
        obrigatorio: false,
        descricao: '',
      },
      {
        id: 'g6',
        tipo: 'texto_longo',
        label: 'Observações de saúde ou conforto',
        placeholder: 'Ex: sinto cansaço nas pernas, preciso de pausas regulares...',
        ordem: 6,
        obrigatorio: false,
        descricao: 'Sua segurança e bem-estar são prioridade absoluta',
      },
    ],
  },
  {
    slug: 'newborn',
    nome: 'Briefing — Ensaio Newborn',
    descricao: 'Informações de segurança, rotina do bebê e preferências dos pais.',
    categoria: 'newborn',
    emoji: '👶',
    tempo_estimado: 2,
    campos: [
      {
        id: 'n1',
        tipo: 'texto_curto',
        label: 'Nome do bebê',
        placeholder: 'Ex: Theo',
        ordem: 1,
        obrigatorio: true,
        descricao: '',
      },
      {
        id: 'n2',
        tipo: 'data',
        label: 'Data de nascimento do bebê',
        placeholder: 'Selecione a data',
        ordem: 2,
        obrigatorio: true,
        descricao: 'Calculamos os dias de vida para adaptar o ritmo da sessão',
      },
      {
        id: 'n3',
        tipo: 'selecao_unica',
        label: 'O nascimento foi a termo?',
        placeholder: '',
        ordem: 3,
        obrigatorio: true,
        opcoes: ['Sim, a termo (38 a 41 semanas)', 'Prematuro (menos de 37 semanas)'],
        descricao: '',
      },
      {
        id: 'n4',
        tipo: 'texto_curto',
        label: 'Cores e paleta de preferência',
        placeholder: 'Ex: tons suaves, off-white, verde oliva, bege',
        ordem: 4,
        obrigatorio: false,
        descricao: '',
      },
      {
        id: 'n5',
        tipo: 'texto_longo',
        label: 'Itens com valor afetivo para incluir',
        placeholder: 'Ex: mantinha bordada pela avó, terço da família, primeiro sapatinho',
        ordem: 5,
        obrigatorio: false,
        descricao: '',
      },
      {
        id: 'n6',
        tipo: 'texto_longo',
        label: 'Cuidados especiais / Observações',
        placeholder: 'Ex: cólicas frequentes, sensibilidade a ruídos...',
        ordem: 6,
        obrigatorio: false,
        descricao: '',
      },
    ],
  },
  {
    slug: 'evento',
    nome: 'Briefing — Eventos & Festas',
    descricao: 'Cobertura de aniversários, batizados, formaturas e eventos corporativos.',
    categoria: 'evento',
    emoji: '🎉',
    tempo_estimado: 3,
    campos: [
      {
        id: 'ev1',
        tipo: 'texto_curto',
        label: 'Tipo e Tema do Evento',
        placeholder: 'Ex: Aniversário Infantil 1 Ano / Confraternização Corporativa',
        ordem: 1,
        obrigatorio: true,
        descricao: '',
      },
      {
        id: 'ev2',
        tipo: 'texto_curto',
        label: 'Homenageado(a) ou Empresa',
        placeholder: 'Ex: Lucca (1 aninho) / Tech Solutions',
        ordem: 2,
        obrigatorio: true,
        descricao: '',
      },
      {
        id: 'ev3',
        tipo: 'texto_curto',
        label: 'Estimativa de convidados',
        placeholder: 'Ex: 60 pessoas',
        ordem: 3,
        obrigatorio: false,
        descricao: '',
      },
      {
        id: 'ev4',
        tipo: 'texto_longo',
        label: 'Momentos principais do cronograma',
        placeholder: 'Ex: Recepção, Parabéns às 19h, Brincadeiras, Discursos...',
        ordem: 4,
        obrigatorio: true,
        descricao: '',
      },
      {
        id: 'ev5',
        tipo: 'texto_longo',
        label: 'Instruções e fotos protocolares',
        placeholder: 'Ex: Fotos na mesa do bolo logo no início com avós e padrinhos',
        ordem: 5,
        obrigatorio: false,
        descricao: '',
      },
    ],
  },
];
