import { CUSTOS_PROP, FAIXAS_PROP, PRODUTOS_PROP, SESSION_REF } from "./schemasCommon.ts";

export const BRIDGE_SCHEMAS: Record<string, Record<string, unknown>> = {
  // ---------- ANÁLISE DE VENDAS ----------
  "lunari.workflow.vendas.resumo": {
    type: "object",
    properties: {
      ano: { type: "number", description: "Ano (ex.: 2026). Padrão: ano corrente." },
      mes: { type: "number", description: "Mês 1-12. Omita para o ano inteiro." },
      categoria: { type: "string", description: "Filtrar por categoria (ex.: Newborn)." },
    },
    additionalProperties: false,
  },
  "lunari.workflow.vendas.compararAnos": {
    type: "object",
    properties: {
      anoBase: { type: "number", description: "Ano principal (padrão: ano corrente)." },
      anoComparacao: { type: "number", description: "Ano de comparação (padrão: ano anterior)." },
      limiteMes: { type: "number", description: "Compara só até este mês (1-12). Automático quando omitido." },
      categoria: { type: "string" },
    },
    additionalProperties: false,
  },
  "lunari.workflow.vendas.metasProgresso": {
    type: "object",
    properties: {
      ano: { type: "number", description: "Ano das metas (padrão: corrente)." },
      mes: { type: "number", description: "Mês de referência 1-12 (padrão: mês atual)." },
    },
    additionalProperties: false,
  },
  "lunari.workflow.photoProductionForYear": {
    type: "object",
    properties: {
      year: { type: "number", description: "Ano (padrão: corrente)." },
      categoria: { type: "string" },
    },
    additionalProperties: false,
  },
  // ---------- LEADS (leitura) ----------
  "lunari.leads.list": {
    type: "object",
    properties: {
      status: { type: "string", description: "Chave do estágio do funil." },
      origem: { type: "string" },
      desde: { type: "string", description: "Data inicial YYYY-MM-DD (criação do lead)." },
      ate: { type: "string", description: "Data final YYYY-MM-DD." },
      search: { type: "string", description: "Parte do nome do lead." },
      arquivados: { type: "string", enum: ["ocultar", "incluir", "somente"] },
      limit: { type: "number" },
    },
    additionalProperties: false,
  },
  "lunari.leads.metrics": {
    type: "object",
    properties: {
      desde: { type: "string", description: "Data inicial YYYY-MM-DD (padrão: 1º de janeiro)." },
      ate: { type: "string", description: "Data final YYYY-MM-DD (padrão: hoje)." },
    },
    additionalProperties: false,
  },
  "lunari.leads.get": {
    type: "object",
    properties: { id: { type: "string", description: "UUID do lead ou parte do nome." } },
    required: ["id"],
    additionalProperties: false,
  },
  "lunari.leads.listStatuses": { type: "object", properties: {}, additionalProperties: false },
  // ---------- PRECIFICAÇÃO ----------
  "lunari.precificacao.getConfiguracao": { type: "object", properties: {}, additionalProperties: false },
  "lunari.precificacao.getEstruturaCustos": { type: "object", properties: {}, additionalProperties: false },
  "lunari.precificacao.listTabelas": { type: "object", properties: {}, additionalProperties: false },
  "lunari.precificacao.diagnostico": { type: "object", properties: {}, additionalProperties: false },
  "lunari.precificacao.getTabelaCategoria": {
    type: "object",
    properties: {
      categoria: { type: "string", description: "Nome da categoria (ex.: Newborn) ou UUID." },
      categoriaId: { type: "string" },
    },
    additionalProperties: false,
  },
  "lunari.precificacao.listPacotesComPreco": {
    type: "object",
    properties: { categoria: { type: "string" }, categoriaId: { type: "string" } },
    additionalProperties: false,
  },
  "lunari.precificacao.getMetas": {
    type: "object", properties: { ano: { type: "number" } }, additionalProperties: false,
  },
  "lunari.precificacao.listCenarios": {
    type: "object", properties: { limit: { type: "number" } }, additionalProperties: false,
  },
  "lunari.precificacao.simularPreco": {
    type: "object",
    properties: {
      horasEstimadas: { type: "number", description: "Horas totais do trabalho (captação + edição + entrega)." },
      markup: { type: "number", description: "Multiplicador sobre o custo. Se omitido, deriva da margem desejada." },
      margemDesejada: { type: "number", description: "Margem de lucro alvo em % (alternativa ao markup)." },
      produtos: PRODUTOS_PROP,
      custosExtras: CUSTOS_PROP,
      custoPorHoraOverride: { type: "number" },
    },
    required: ["horasEstimadas"],
    additionalProperties: false,
  },
  "lunari.precificacao.simularFotoExtra": {
    type: "object",
    properties: {
      quantidade: { type: "number" },
      pacote: { type: "string", description: "Nome do pacote (ou UUID em pacoteId)." },
      pacoteId: { type: "string" },
      categoria: { type: "string" },
      categoriaId: { type: "string" },
    },
    required: ["quantidade"],
    additionalProperties: false,
  },
  "lunari.precificacao.simularPacote": {
    type: "object",
    properties: {
      pacote: { type: "string", description: "Nome do pacote." },
      pacoteId: { type: "string" },
      fotosExtras: { type: "number" },
      valorAdicional: { type: "number" },
      desconto: { type: "number" },
    },
    additionalProperties: false,
  },
  "lunari.precificacao.simularImpactoTabela": {
    type: "object",
    properties: {
      escopo: { type: "string", enum: ["global", "categoria"] },
      categoria: { type: "string" },
      categoriaId: { type: "string" },
      faixas: FAIXAS_PROP,
      quantidades: { type: "array", items: { type: "number" } },
    },
    required: ["faixas"],
    additionalProperties: false,
  },
  "lunari.precificacao.criarPacotePrecificado": {
    type: "object",
    properties: {
      nome: { type: "string", description: "Nome do novo pacote." },
      categoria: { type: "string", description: "Nome da categoria (criada se não existir com criarCategoria=true)." },
      categoriaId: { type: "string" },
      criarCategoria: { type: "boolean", description: "Cria a categoria quando ela não existir." },
      horasEstimadas: { type: "number", description: "Horas do trabalho — base do cálculo." },
      markup: { type: "number" },
      margemDesejada: { type: "number", description: "Margem alvo em % (alternativa ao markup)." },
      produtos: PRODUTOS_PROP,
      custosExtras: CUSTOS_PROP,
      valorBase: { type: "number", description: "Se informado, ignora o cálculo e usa este preço." },
      arredondarPara: { type: "number", description: "Arredonda o preço para múltiplos deste valor (ex.: 10)." },
      fotosIncluidas: { type: "number" },
      valorFotoExtra: { type: "number", description: "Se omitido, usa a tabela vigente da categoria." },
    },
    required: ["nome"],
    additionalProperties: false,
  },
  "lunari.precificacao.salvarCenario": {
    type: "object",
    properties: {
      nome: { type: "string", description: "Nome do cenário (ex.: 'Newborn 2026')." },
      horasEstimadas: { type: "number" },
      markup: { type: "number" },
      margemDesejada: { type: "number" },
      produtos: PRODUTOS_PROP,
      custosExtras: CUSTOS_PROP,
    },
    required: ["nome", "horasEstimadas"],
    additionalProperties: false,
  },
  "lunari.precificacao.updatePacotePreco": {
    type: "object",
    properties: {
      pacote: { type: "string", description: "Nome do pacote." },
      pacoteId: { type: "string" },
      valorBase: { type: "number" },
      valorFotoExtra: { type: "number" },
      fotosIncluidas: { type: "number" },
    },
    additionalProperties: false,
  },
  "lunari.precificacao.upsertTabelaGlobal": {
    type: "object",
    properties: { nome: { type: "string" }, faixas: FAIXAS_PROP, usarValorFixoPacote: { type: "boolean" } },
    required: ["faixas"],
    additionalProperties: false,
  },
  "lunari.precificacao.upsertTabelaCategoria": {
    type: "object",
    properties: {
      categoria: { type: "string" },
      categoriaId: { type: "string" },
      nome: { type: "string" },
      faixas: FAIXAS_PROP,
      usarValorFixoPacote: { type: "boolean" },
    },
    required: ["faixas"],
    additionalProperties: false,
  },
  "lunari.precificacao.setModelo": {
    type: "object",
    properties: { modelo: { type: "string", enum: ["fixo", "global", "categoria"] } },
    required: ["modelo"],
    additionalProperties: false,
  },
  "lunari.precificacao.updateMargemEHoras": {
    type: "object",
    properties: {
      margemLucroDesejada: { type: "number", description: "Margem alvo em %." },
      percentualProLabore: { type: "number" },
      horasDisponiveis: { type: "number", description: "Horas produtivas por dia." },
      diasTrabalhados: { type: "number", description: "Dias por semana." },
    },
    additionalProperties: false,
  },
  "lunari.precificacao.setMetas": {
    type: "object",
    properties: {
      ano: { type: "number" },
      metaFaturamentoAnual: { type: "number" },
      metaLucroAnual: { type: "number" },
      usarMetasPersonalizadas: { type: "boolean" },
    },
    additionalProperties: false,
  },
  "lunari.configuracoes.listCategorias": { type: "object", properties: {}, additionalProperties: false },
  "lunari.configuracoes.listPacotes": {
    type: "object",
    properties: { categoria: { type: "string" }, categoriaId: { type: "string" } },
    additionalProperties: false,
  },
  "lunari.configuracoes.createCategoria": {
    type: "object",
    properties: { nome: { type: "string" }, cor: { type: "string" } },
    required: ["nome"],
    additionalProperties: false,
  },
  "lunari.configuracoes.createPacote": {
    type: "object",
    properties: {
      nome: { type: "string", description: "Nome do pacote." },
      categoria: { type: "string", description: "Nome da categoria." },
      categoriaId: { type: "string" },
      valorBase: { type: "number" },
      valorFotoExtra: { type: "number" },
      fotosIncluidas: { type: "number" },
    },
    required: ["nome"],
    additionalProperties: false,
  },

  "lunari.workflow.getCardBySession": {
    type: "object", properties: { ...SESSION_REF }, additionalProperties: false,
  },
  "lunari.workflow.getSessionFinancials": {
    type: "object", properties: { ...SESSION_REF }, additionalProperties: false,
  },
  "lunari.workflow.diagnoseSession": {
    type: "object", properties: { ...SESSION_REF }, additionalProperties: false,
  },
  "lunari.workflow.produto.listBySession": {
    type: "object", properties: { ...SESSION_REF }, additionalProperties: false,
  },
  "lunari.workflow.produto.listPending": {
    type: "object", properties: { limit: { type: "number" } }, additionalProperties: false,
  },
  "lunari.workflow.listSessionsByPaymentStatus": {
    type: "object",
    properties: {
      statusFinanceiro: { type: "string", description: "pendente, parcial, pago ou quitado." },
      limit: { type: "number" },
    },
    additionalProperties: false,
  },
  "lunari.workflow.statusOptions": { type: "object", properties: {}, additionalProperties: false },
  "lunari.workflow.metricsForMonth": {
    type: "object",
    properties: {
      year: { type: "number", description: "Ano (padrão: atual)." },
      month: { type: "number", description: "Mês 1-12 (padrão: atual)." },
    },
    additionalProperties: false,
  },
  "lunari.workflow.photoProductionForMonth": {
    type: "object",
    properties: { year: { type: "number" }, month: { type: "number" }, categoria: { type: "string" } },
    additionalProperties: false,
  },
  "lunari.workflow.metricsForRange": {
    type: "object",
    properties: {
      start: { type: "string", description: "Data inicial YYYY-MM-DD." },
      end: { type: "string", description: "Data final YYYY-MM-DD." },
      granularity: { type: "string", enum: ["day", "week", "month"] },
      includeHistorico: { type: "boolean" },
    },
    additionalProperties: false,
  },
  "lunari.workflow.analytics.summary": {
    type: "object",
    properties: {
      start: { type: "string" },
      end: { type: "string" },
      includeHistorico: { type: "boolean" },
    },
    additionalProperties: false,
  },
  "lunari.workflow.updateFields": {
    type: "object",
    properties: {
      ...SESSION_REF,
      descricao: { type: "string" },
      observacoes: { type: "string" },
      detalhes: { type: "string" },
      categoria: { type: "string" },
      pacote: { type: "string" },
      data_sessao: { type: "string", description: "Data YYYY-MM-DD." },
      hora_sessao: { type: "string", description: "Hora HH:MM." },
      desconto: { type: "number", description: "Desconto em reais." },
      valor_adicional: { type: "number", description: "Valor adicional em reais." },
      valor_base_pacote: { type: "number" },
      valor_foto_extra: { type: "number", description: "Preço unitário da foto extra." },
      qtd_fotos_extra: { type: "number" },
    },
    additionalProperties: false,
  },
  "lunari.workflow.advanceCard": {
    type: "object",
    properties: { ...SESSION_REF, toStatus: { type: "string", description: "Etapa de destino (ver statusOptions)." } },
    required: ["toStatus"],
    additionalProperties: false,
  },
  "lunari.workflow.addPayment": {
    type: "object",
    properties: {
      ...SESSION_REF,
      valor: { type: "number", description: "Valor em reais (ex.: 250.00)." },
      data: { type: "string", description: "Data do pagamento YYYY-MM-DD (padrão: hoje)." },
      formaPagamento: { type: "string", description: "PIX, Cartão, Dinheiro, Transferência..." },
      descricao: { type: "string", description: "Observação do lançamento." },
    },
    required: ["valor"],
    additionalProperties: false,
  },
  "lunari.workflow.refundPayment": {
    type: "object",
    properties: {
      transactionId: { type: "string", description: "UUID do pagamento a estornar." },
      motivo: { type: "string" },
    },
    required: ["transactionId"],
    additionalProperties: false,
  },
  "lunari.workflow.deleteSession": {
    type: "object",
    properties: { ...SESSION_REF, force: { type: "boolean", description: "Excluir mesmo com lançamentos financeiros." } },
    additionalProperties: false,
  },

  "lunari.agenda.appointments.create": {
    type: "object",
    properties: {
      title: { type: "string", description: "Título do agendamento." },
      date: { type: "string", description: "Data YYYY-MM-DD." },
      time: { type: "string", description: "Hora HH:MM." },
      type: { type: "string", description: "Categoria/tipo (ex.: Newborn, Família)." },
      status: { type: "string", enum: ["confirmado", "a confirmar"] },
      clienteId: { type: "string", description: "UUID do cliente." },
      clienteNome: { type: "string", description: "Nome do cliente — resolvido automaticamente; pergunte se houver dúvida." },
      semCliente: { type: "boolean", description: "Só para bloqueio pessoal sem cliente. Confirme com o usuário antes." },
      description: { type: "string" },
      durationMinutes: { type: "number", description: "Duração em minutos (padrão 60)." },
      force: { type: "boolean", description: "Criar mesmo havendo conflito de horário." },
    },
    required: ["date"],
    additionalProperties: false,
  },
  "lunari.agenda.appointments.update": {
    type: "object",
    properties: {
      id: { type: "string" },
      title: { type: "string" },
      date: { type: "string" },
      time: { type: "string" },
      type: { type: "string" },
      status: { type: "string", enum: ["confirmado", "a confirmar"] },
      description: { type: "string" },
      durationMinutes: { type: "number" },
      clienteNome: { type: "string" },
      clienteId: { type: "string" },
    },
    required: ["id"],
    additionalProperties: false,
  },
  "lunari.tasks.create": {
    type: "object",
    properties: {
      title: { type: "string" },
      description: { type: "string" },
      notes: { type: "string" },
      dueDate: { type: "string", description: "Data YYYY-MM-DD." },
      priority: { type: "string", enum: ["low", "medium", "high"] },
      status: { type: "string", description: "todo (padrão) ou done." },
      category: { type: "string" },
      checklistItems: { type: "array", items: { type: "string" }, description: "Itens do checklist." },
      clienteNome: { type: "string", description: "Vincula a tarefa a um cliente pelo nome." },
      relatedSessionId: { type: "string" },
    },
    required: ["title"],
    additionalProperties: false,
  },
  "lunari.tasks.update": {
    type: "object",
    properties: {
      id: { type: "string" },
      title: { type: "string" },
      description: { type: "string" },
      notes: { type: "string" },
      dueDate: { type: "string" },
      priority: { type: "string", enum: ["low", "medium", "high"] },
      status: { type: "string" },
      category: { type: "string" },
    },
    required: ["id"],
    additionalProperties: false,
  },
  "lunari.finance.transaction.create": {
    type: "object",
    properties: {
      valor: { type: "number", description: "Valor em reais (positivo)." },
      item: { type: "string", description: "Nome do item financeiro (ex.: 'Schlosser', 'Aluguel'). Resolvido por busca." },
      itemId: { type: "string", description: "UUID do item (alternativa a 'item')." },
      grupo: {
        type: "string",
        description: "Filtra a busca do item pelo grupo.",
        enum: ["Despesa Fixa", "Despesa Variável", "Investimento", "Receita Não Operacional", "Receita Operacional"],
      },
      dataVencimento: { type: "string", description: "YYYY-MM-DD (padrão: hoje)." },
      dataCompetencia: { type: "string", description: "YYYY-MM-DD." },
      status: { type: "string", enum: ["Pago", "Agendado", "Faturado"], description: "Padrão: Pago." },
      observacoes: { type: "string" },
    },
    required: ["valor"],
    additionalProperties: false,
  },
  "lunari.agenda.slot.check": {
    type: "object",
    properties: {
      date: { type: "string" },
      time: { type: "string" },
      durationMinutes: { type: "number" },
      excludeAppointmentId: { type: "string" },
    },
    required: ["date", "time"],
    additionalProperties: false,
  },
  "lunari.agenda.availability.findNext": {
    type: "object",
    properties: {
      fromDate: { type: "string", description: "YYYY-MM-DD (padrão: hoje)." },
      fromTime: { type: "string", description: "HH:MM (padrão: 08:00)." },
      horizonDays: { type: "number", description: "Janela de busca em dias (padrão 30)." },
      durationMinutes: { type: "number" },
    },
    additionalProperties: false,
  },
};
